### ISSUE TITLE
Merge efforts in one repo

### ISSUE THREAD

**Issue by zenorocha** [vigo/textmate2-dracula-theme#1]
Hello @vigo!

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way!

I was wondering if you are interested in merging efforts with the existing Textmate theme (https://github.com/dracula/textmate). Is there anything you would like to change from that one? Would you be interested in becoming a maintainer on that project?

What do you think?

**Comment by vigo** [comment]
well, sounds lovely. i'd like to do that :)

**Comment by zenorocha** [comment]
Awesome! I just invited you to the organization, let me know when you accept it and then we can move forward.

**Comment by vigo** [comment]
yeah approved!

**Comment by zenorocha** [comment]
Moved discussion to https://github.com/dracula/textmate/issues/1 ;D
